import React from "react";
import GuideList from './GuideList';
import  { MFEPGProps } from './MF-EPGProps';

class EPG extends React.Component<MFEPGProps> {
    render() {
        const {
            Channels,
            channelRowHeight,
            timeLineHeight,
            channelRowHeaderWidth,
            expandedViewHeight,
            defaultChannelLogoSrc,
            defaultShowImage,
            recordButtonIcon,
            watchLiveButtonIcon,
            infoButtonIcon,
            dayOptions,
            onPlay,
            onRecord,
            onInfoClick,
            timeBlockWidth,
            fetchData,
            gapBwTwoChRows,
            channelBlockStyle,
            chNameTextMaxWidth,
            channelLogoStyle,
            channelBlockExpansionStyle,
            channelExpImageBlk,
            channelExpImg,
            channelNumberTextStyle,
            channelNameTextStyle,
            showsRowContainer,
            chRowExpansionStyle,
            noShowBlockStyle,
            noShowTextStyle,
            showBlockStyle,
            showTextStyle,
            gapBwTwoShows,
            showDetailsContainer,
            showDetailsNameRow,
            showLabelStyle,
            showLabelTextStyle,
            showNameStyle,
            showDetailsStyle,
            showDescStyle,
            chActionsViewStyle,
            progressBarViewStyle,
            showDetailsViewStyle,
            showActionsViewStyle,
            progressBarStyle,
            progressStyle,
            actionButtonHeight,
            actionButtonStyle,
            actionLabelStyle,
            actionIconStyle,
            timelineRowStyle,
            timeTextStyle,
            timeBlockStyle,
            whichDayContainer,
            pickerStyle,
            guideListStyle,
            rowHeaderStyle
        } = this.props;
        return(
            <GuideList
                Channels={Channels}
                fetchData={fetchData}
                defaultChannelLogoSrc={defaultChannelLogoSrc}
                defaultShowImage={defaultShowImage}
                recordButtonIcon={recordButtonIcon}         
                watchLiveButtonIcon={watchLiveButtonIcon}         
                infoButtonIcon={infoButtonIcon}
                onPlay={onPlay}     
                onRecord={onRecord}     
                onInfoClick={onInfoClick}   
                dayOptions={dayOptions}
                channelRowHeaderWidth={channelRowHeaderWidth}
                timeLineHeight={timeLineHeight}
                channelRowHeight={channelRowHeight}
                expandedViewHeight={expandedViewHeight}
                timeBlockWidth={timeBlockWidth}
                gapBwTwoChRows={gapBwTwoChRows}
                channelBlockStyle={channelBlockStyle}
                chNameTextMaxWidth={chNameTextMaxWidth}
                channelLogoStyle={channelLogoStyle}
                channelBlockExpansionStyle={channelBlockExpansionStyle}
                channelExpImageBlk={channelExpImageBlk}
                channelExpImg={channelExpImg}
                channelNumberTextStyle={channelNumberTextStyle}
                channelNameTextStyle={channelNameTextStyle}
                showsRowContainer={showsRowContainer}
                chRowExpansionStyle={chRowExpansionStyle}
                noShowBlockStyle={noShowBlockStyle}
                noShowTextStyle={noShowTextStyle}
                showBlockStyle={showBlockStyle}
                showTextStyle={showTextStyle}
                gapBwTwoShows={gapBwTwoShows}
                showDetailsContainer={showDetailsContainer}
                showDetailsNameRow={showDetailsNameRow}
                showLabelStyle={showLabelStyle}
                showLabelTextStyle={showLabelTextStyle}
                showNameStyle={showNameStyle}
                showDetailsStyle={showDetailsStyle}
                showDescStyle={showDescStyle}
                chActionsViewStyle={chActionsViewStyle}
                progressBarViewStyle={progressBarViewStyle}
                showDetailsViewStyle={showDetailsViewStyle}
                showActionsViewStyle={showActionsViewStyle}
                progressBarStyle={progressBarStyle}
                progressStyle={progressStyle}
                actionButtonHeight={actionButtonHeight}
                actionButtonStyle={actionButtonStyle}
                actionLabelStyle={actionLabelStyle}
                actionIconStyle={actionIconStyle}
                timelineRowStyle={timelineRowStyle}
                timeTextStyle={timeTextStyle}
                timeBlockStyle={timeBlockStyle}
                whichDayContainer={whichDayContainer}
                pickerStyle={pickerStyle}
                guideListStyle={guideListStyle}
            />
        );
    }
}

export default EPG ;